### ISSUE TITLE
An CUDA error occurred using the latest version of the rasterizer

### ISSUE THREAD

**Issue by Rosetta-Leong** [Zerg-Overmind/diff-gaussian-rasterization#6]
**When I use the latest version of the rasterizer(commit: **2917773c24af4decc298e511c3bf65c5397689fd**), I encounter the following problems:**
![1721114904719](https://github.com/user-attachments/assets/fb258c85-baa8-40f8-a247-0e43523bc84b)
There seems to be an illegal memory access problem with the rasterizer implementation causing CUDA to report an error.
**But strangely, I was able to use the older version of the rasterizer(commit: ade8f028d7895e37d337e5313bc0952cc2c331dd) and it worked fine, which confused me.** 

I would like to ask what major changes were made in the latest two commits? Do I need to make any corresponding changes in usage? I would greatly appreciate it if you could provide some information.

P.S. This is my code for using the rasterizer, 
![1721115183693](https://github.com/user-attachments/assets/9360fa09-131e-49e7-b466-f82e72f8d6dc)

**Comment by hanxuel** [comment]
I met the same error when using the latest code, could you please check the latest version?
[rank6]: Traceback (most recent call last):
[rank6]:   File "main.py", line 299, in <module>
[rank6]:     main()
[rank6]:   File "main.py", line 146, in main
[rank6]:     accelerator.backward(loss)
[rank6]:   File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 2001, in backward
[rank6]:     loss.backward(**kwargs)
[rank6]:   File "/usr/local/lib/python3.8/dist-packages/torch/_tensor.py", line 525, in backward
[rank6]:     torch.autograd.backward(
[rank6]:   File "/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py", line 267, in backward
[rank6]:     _engine_run_backward(
[rank6]:   File "/usr/local/lib/python3.8/dist-packages/torch/autograd/graph.py", line 744, in _engine_run_backward
[rank6]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank6]: RuntimeError: CUDA error: an illegal memory access was encountered
[rank6]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank6]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[rank6]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by hanxuel** [comment]
> **When I use the latest version of the rasterizer(commit: [2917773](https://github.com/Zerg-Overmind/diff-gaussian-rasterization/commit/2917773c24af4decc298e511c3bf65c5397689fd)), I encounter the following problems:** ![1721114904719](https://private-user-images.githubusercontent.com/55617428/348984224-fb258c85-baa8-40f8-a247-0e43523bc84b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMzkwMTIsIm5iZiI6MTcyNDEzODcxMiwicGF0aCI6Ii81NTYxNzQyOC8zNDg5ODQyMjQtZmIyNThjODUtYmFhOC00MGY4LWEyNDctMGU0MzUyM2JjODRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA3MjUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMjdmNTUwN2NhNGExYTU2ZTBkNzEyNWRiM2E0ZDg3YmQ1YjVlZTA0ZmNjMjFkNjQ5MjgwNWYxMjhjMjljMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mJ7nHXgBfZGpBKWPYmD0imLCUJdBMJRy7-p_A_aLc1I) There seems to be an illegal memory access problem with the rasterizer implementation causing CUDA to report an error. **But strangely, I was able to use the older version of the rasterizer(commit: [ade8f02](https://github.com/Zerg-Overmind/diff-gaussian-rasterization/commit/ade8f028d7895e37d337e5313bc0952cc2c331dd)) and it worked fine, which confused me.**
> 
> I would like to ask what major changes were made in the latest two commits? Do I need to make any corresponding changes in usage? I would greatly appreciate it if you could provide some information.
> 
> P.S. This is my code for using the rasterizer, ![1721115183693](https://private-user-images.githubusercontent.com/55617428/348996377-9360fa09-131e-49e7-b466-f82e72f8d6dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMzkwMTIsIm5iZiI6MTcyNDEzODcxMiwicGF0aCI6Ii81NTYxNzQyOC8zNDg5OTYzNzctOTM2MGZhMDktMTMxZS00OWU3LWI0NjYtZjgyZTcyZjhkNmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA3MjUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlZGVlOTQ2MmY0OGVjYmY3OWQ1MzM3ZjA5ZjIyMGJiMTUzOTExMWZjNWQ0MGIyYWY3ZjNkZTJiMjAwYzBiMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.05iGW_d2hzHPIbCurjF1EEpmpJIifJD892tDtp8bI4k)


Or could you please share with me the previous workable version?

**Comment by Rosetta-Leong** [comment]
> > **When I use the latest version of the rasterizer(commit: [2917773](https://github.com/Zerg-Overmind/diff-gaussian-rasterization/commit/2917773c24af4decc298e511c3bf65c5397689fd)), I encounter the following problems:** ![1721114904719](https://private-user-images.githubusercontent.com/55617428/348984224-fb258c85-baa8-40f8-a247-0e43523bc84b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMzkwMTIsIm5iZiI6MTcyNDEzODcxMiwicGF0aCI6Ii81NTYxNzQyOC8zNDg5ODQyMjQtZmIyNThjODUtYmFhOC00MGY4LWEyNDctMGU0MzUyM2JjODRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA3MjUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMjdmNTUwN2NhNGExYTU2ZTBkNzEyNWRiM2E0ZDg3YmQ1YjVlZTA0ZmNjMjFkNjQ5MjgwNWYxMjhjMjljMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mJ7nHXgBfZGpBKWPYmD0imLCUJdBMJRy7-p_A_aLc1I) There seems to be an illegal memory access problem with the rasterizer implementation causing CUDA to report an error. **But strangely, I was able to use the older version of the rasterizer(commit: [ade8f02](https://github.com/Zerg-Overmind/diff-gaussian-rasterization/commit/ade8f028d7895e37d337e5313bc0952cc2c331dd)) and it worked fine, which confused me.**
> > I would like to ask what major changes were made in the latest two commits? Do I need to make any corresponding changes in usage? I would greatly appreciate it if you could provide some information.
> > P.S. This is my code for using the rasterizer, ![1721115183693](https://private-user-images.githubusercontent.com/55617428/348996377-9360fa09-131e-49e7-b466-f82e72f8d6dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMzkwMTIsIm5iZiI6MTcyNDEzODcxMiwicGF0aCI6Ii81NTYxNzQyOC8zNDg5OTYzNzctOTM2MGZhMDktMTMxZS00OWU3LWI0NjYtZjgyZTcyZjhkNmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA3MjUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlZGVlOTQ2MmY0OGVjYmY3OWQ1MzM3ZjA5ZjIyMGJiMTUzOTExMWZjNWQ0MGIyYWY3ZjNkZTJiMjAwYzBiMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.05iGW_d2hzHPIbCurjF1EEpmpJIifJD892tDtp8bI4k)
> 
> Or could you please share with me the previous workable version?

commit: [ade8f02](https://github.com/Zerg-Overmind/diff-gaussian-rasterization/commit/ade8f028d7895e37d337e5313bc0952cc2c331dd)

**Comment by penghaohsu** [comment]
> > > **When I use the latest version of the rasterizer(commit: [2917773](https://github.com/Zerg-Overmind/diff-gaussian-rasterization/commit/2917773c24af4decc298e511c3bf65c5397689fd)), I encounter the following problems:** ![1721114904719](https://private-user-images.githubusercontent.com/55617428/348984224-fb258c85-baa8-40f8-a247-0e43523bc84b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMzkwMTIsIm5iZiI6MTcyNDEzODcxMiwicGF0aCI6Ii81NTYxNzQyOC8zNDg5ODQyMjQtZmIyNThjODUtYmFhOC00MGY4LWEyNDctMGU0MzUyM2JjODRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA3MjUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMjdmNTUwN2NhNGExYTU2ZTBkNzEyNWRiM2E0ZDg3YmQ1YjVlZTA0ZmNjMjFkNjQ5MjgwNWYxMjhjMjljMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mJ7nHXgBfZGpBKWPYmD0imLCUJdBMJRy7-p_A_aLc1I) There seems to be an illegal memory access problem with the rasterizer implementation causing CUDA to report an error. **But strangely, I was able to use the older version of the rasterizer(commit: [ade8f02](https://github.com/Zerg-Overmind/diff-gaussian-rasterization/commit/ade8f028d7895e37d337e5313bc0952cc2c331dd)) and it worked fine, which confused me.**
> > > I would like to ask what major changes were made in the latest two commits? Do I need to make any corresponding changes in usage? I would greatly appreciate it if you could provide some information.
> > > P.S. This is my code for using the rasterizer, ![1721115183693](https://private-user-images.githubusercontent.com/55617428/348996377-9360fa09-131e-49e7-b466-f82e72f8d6dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMzkwMTIsIm5iZiI6MTcyNDEzODcxMiwicGF0aCI6Ii81NTYxNzQyOC8zNDg5OTYzNzctOTM2MGZhMDktMTMxZS00OWU3LWI0NjYtZjgyZTcyZjhkNmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA3MjUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlZGVlOTQ2MmY0OGVjYmY3OWQ1MzM3ZjA5ZjIyMGJiMTUzOTExMWZjNWQ0MGIyYWY3ZjNkZTJiMjAwYzBiMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.05iGW_d2hzHPIbCurjF1EEpmpJIifJD892tDtp8bI4k)
> > 
> > 
> > Or could you please share with me the previous workable version?
> 
> commit: [ade8f02](https://github.com/Zerg-Overmind/diff-gaussian-rasterization/commit/ade8f028d7895e37d337e5313bc0952cc2c331dd)

I have met the same problem. Does this previous version work correctly?
